### ISSUE TITLE
Cascade Classification TODO list

### ISSUE THREAD

**Issue by StevenPuttemans** [StevenPuttemans/opencv#9]
This list will contain all the TODO things that are currently needed to create a more versatile object detection framework in OpenCV based on cascade classification.

- [ ] The `opencv_createsamples` tool only allows to use relative paths with the `-info` parameter. If an absolute path is given, then the location from which data is read, will be corrupted. This should be fixed, since a user should be aware of his own behaviour (filling info.txt with relative or absolute paths).
- [ ] There is a [known issue](https://github.com/opencv/opencv/issues/7480) where the cascade classifier keeps collecting negative training samples even if it is not possible. 
- [ ] The usage of a mask defining regions where the cascade should work would be a nice addition. This can be in the form of an overload function with a given binary mask image.
- [ ] Investigate a uniform score handling for cascade classifiers. Current score is dependant on the given test images resolution and thus with a mixed dataset, results are way off. This can be fixed with either a per area solution or by returning a better score for each window passing through the cascade.
- [ ] Re-add the option to retrieve rejection levels and scores of all windows passing through the cascade *(needed for better precision recall evaluation)*
- [ ] Detection at a specific position in the image. Basically running the runAt function only once, which is now hidden in the non-public part of the class.
